# Generated by Django 3.1.5 on 2021-01-16 00:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20210115_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnastoliErgasias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateField()),
                ('to_time', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'anastoli_ergasias',
            },
        ),
        migrations.CreateModel(
            name='AdeiaErgasias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateField()),
                ('to_time', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adeia_ergasias',
            },
        ),
        migrations.CreateModel(
            name='AdeiaEidikoySkopoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateField()),
                ('to_time', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('children', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('status', models.SmallIntegerField(choices=[(-1, 'Not Approved'), (0, 'Pending'), (1, 'Approved')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adeia_eidikoy_skopoy',
            },
        ),
    ]
