# Generated by Django 3.1.5 on 2021-01-19 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_has_child_under_12'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0002_auto_20210116_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='adeiaergasias',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Not Approved'), (0, 'Pending'), (1, 'Approved')], default=0),
        ),
        migrations.AddField(
            model_name='anastoliergasias',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Not Approved'), (0, 'Pending'), (1, 'Approved')], default=0),
        ),
        migrations.CreateModel(
            name='Tilergasia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateField()),
                ('to_time', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.SmallIntegerField(choices=[(-1, 'Not Approved'), (0, 'Pending'), (1, 'Approved')], default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tilergasia',
            },
        ),
    ]
