# Generated by Django 3.1.5 on 2021-01-14 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdeiaErgasias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateField()),
                ('to_time', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adeia_ergasias',
            },
        ),
        migrations.CreateModel(
            name='AdeiaEidikoySkopoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateField()),
                ('to_time', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adeia_eidikoy_skopoy',
            },
        ),
    ]
