# Generated by Django 3.1.5 on 2021-01-16 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210115_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_child_under_12',
        ),
    ]
